# Generated by Django 5.0.6 on 2024-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rentalrecord_member_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrecord',
            name='rental_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentalrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
